[Unit]
After=graphical-session.target dconf.service xdg-desktop-portal.service cliphist.service
Wants=dconf.service xdg-desktop-portal.service cliphist.service

[Service]
Slice=background-graphical.slice
