gui:
  language: "en"
  nerdFontsVersion: "3"
  scrollHeight: 10
  showNumstatInFilesView: true
  theme:
    activeBorderColor:
      - "#e89a49"
      - bold
    inactiveBorderColor:
      - "#91887d"
    searchingActiveBorderColor:
      - "#d99148"
      - bold
    optionsTextColor:
      - "#66abc6"
    selectedLineBgColor:
      - "#3c3b36"
    inactiveViewSelectedLineBgColor:
      - "#30302c"
    cherryPickedCommitFgColor:
      - "#66abc6"
    cherryPickedCommitBgColor:
      - "#30302c"
    markedBaseCommitFgColor:
      - "#b991db"
    markedBaseCommitBgColor:
      - "#30302c"
    unstagedChangesColor:
      - "#db8935"
    defaultFgColor:
      - "#c9c0b1"
git:
  overrideGpg: true
  diffRenderers:
    - colorArg: always
      command: "delta --dark --paging=never --commit-style box --true-color always"
promptToReturnFromSubprocess: false
disableStartupPopups: true
