# heme = "dracula"
theme = "dracula"
icons = "material-nf"
# icons = "awesome5"

[[block]]
block = "focused_window"
max_width = 50

[[block]]
block = "music"
buttons = ["play", "next"]
on_collapsed_click = "qmmp"

[[block]]
block = "cpu"
interval = 1
#format = "{barchart} {utilization}"

[[block]]
block = "net"
device = "ethMain"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used} /{mem_total}"
clickable = false

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
unit = "GB"
warning = 20.0
alert = 10.0
alert_absolute = true
format = "{icon} {path}{available}"

[[block]]
block = "load"
interval = 1
format = "{1m} {5m}"

[[block]]
block = "pacman"
interval = 900
critical_updates_regex = "(linux|linux-lts|linux-zen)"
aur_command = "paru -Qua"

[[block]]
block = "weather"
format = "{weather} {temp};{wind} mph {direction}"
service = { name = "openweathermap", api_key = "0b5b73641d85344cfe316696d54b6887", city_id = "5020859", units = "imperial" }

[[block]]
block = "sound"
step_width = 5

[[block]]
block = "time"
format = "%a %m-%d %R"
