[tools]
# Complex
"aqua:apache/maven" = "latest"
"aqua:astral-sh/uv" = "latest"
"aqua:dathere/qsv" = "latest"
"aqua:dprint/dprint" = "latest"
"aqua:duckdb/duckdb" = "latest"
"aqua:gradle/gradle" = "latest"
"aqua:Myriad-Dreamin/tinymist" = "latest"
"aqua:pnpm/pnpm" = "latest"
"aqua:rust-lang/rust-analyzer" = "latest"
"aqua:skaji/relocatable-perl" = "latest"
"aqua:tamasfe/taplo" = "latest"
"github:coursier/coursier" = "latest"
"github:skim-rs/skim" = "latest"

# "asdf:mise-plugins/mise-sbt" = "1.12.13"
"conda:sbt" = "latest"
"vfox:mise-plugins/vfox-scala" = "latest"

# Simple
age = "latest"
bun = "latest"
fnox = "latest"
go = "1.26"
lua = "5.1"
node = "26"
python = "3.14"
sops = "latest"
zig = "0.16"

# Java
java = "temurin-26"

# Go tools
"aqua:charmbracelet/gum" = "latest"
"aqua:dominikh/go-tools/staticcheck" = "latest"
"aqua:golangci/golangci-lint" = "2"
"aqua:hadolint/hadolint" = "latest"
"aqua:itchyny/gojq" = "latest"
"aqua:LuaLS/lua-language-server" = "latest"
"aqua:mr-karan/doggo" = "latest"
"aqua:muesli/duf" = "latest"
"aqua:mvdan/gofumpt" = "latest"
"aqua:mvdan/sh" = "latest"
"aqua:rest-sh/restish" = "latest"
"aqua:segmentio/golines" = "latest"

"github:a-h/templ" = "latest"
"github:docker/docker-language-server" = "latest"
"github:johnkerl/miller" = "latest"
"github:marwan-at-work/mod" = "latest"
"github:oligot/go-mod-upgrade" = "latest"
"github:psampaz/go-mod-outdated" = "latest"
"github:Zxilly/go-size-analyzer" = "latest"

# Go repos
"go:github.com/icholy/gomajor" = "latest"
"go:github.com/noperator/jqfmt/cmd/jqfmt" = "latest"
"go:github.com/noperator/sol/cmd/sol" = "latest"
"go:golang.org/x/tools/cmd/stringer" = "latest"
"go:golang.org/x/tools/gopls" = "latest"

# Node tools
"npm:@biomejs/biome" = "latest"
"npm:@bufbuild/buf" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:mcp-hub" = "latest"
"npm:oxfmt" = "latest"
"npm:prettier" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"

# Python tools
"pipx:black" = "latest"
"pipx:codespell" = "latest"
"pipx:httpie" = "latest"
"pipx:ipython" = "latest"
"pipx:isort" = "latest"
"pipx:pyright" = "latest"
"pipx:ruff" = "latest"

# Renames
[tools."github:dmarkham/enumer"]
version = "latest"
rename_exe = "enumer"

[settings]
disable_hints = ["*"]
experimental = true

http_timeout = "5m"

npm.package_manager = "bun"
pipx.uvx = true
python.uv_venv_auto = "create|source"

minimum_release_age = "2d"
env_cache = true

use_versions_host = true
auto_install = false
prefer_offline = true

erlang.compile = false
node.compile = false
python.compile = false
ruby.compile = false
