-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(1a9fff)",
			inactive_border = "rgb(55585d)",
		},
	},
	group = {
		col = {
			border_active = "rgb(1a9fff)",
			border_inactive = "rgb(55585d)",
			border_locked_active = "rgb(f44336)",
			border_locked_inactive = "rgb(55585d)",
		},
		groupbar = {
			col = {
				active = "rgb(1a9fff)",
				inactive = "rgb(55585d)",
				locked_active = "rgb(f44336)",
				locked_inactive = "rgb(55585d)",
			},
		},
	},
})
