-- Auto-generated by DMS - do not edit manually (Lua converted)

hl.env("HYPRCURSOR_THEME", "Oxygen_Zion")
hl.env("XCURSOR_THEME", "Oxygen_Zion")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_SIZE", "24")
