-- Auto-generated by DMS — do not edit manually

hl.config({
	general = {
		gaps_in = 4,
		gaps_out = 0,
		border_size = 0,
		resize_on_border = true,
	},
	decoration = {
		rounding = 0,
	},
})

hl.layer_rule({
	match = { namespace = "^dms:.*$" },
	xray = true,
})

hl.layer_rule({
	match = { namespace = "^dms:bar$" },
	xray = true,
})
