-- Auto-generated by DMS - do not edit manually (Lua converted)

hl.monitor({
	output = "DP-2",
	mode = "3840x2160@59.997",
	position = "2560x0",
	scale = 1.5,
	vrr = 1,
})

hl.monitor({
	output = "DP-1",
	mode = "3840x2160@119.910",
	position = "0x0",
	scale = 1.5,
	vrr = 1,
})
