"$schema" = 'https://starship.rs/config-schema.json'

right_format = """
$golang\
$python\
$rust\
[](fg:color_blue bg:color_bg1)\
$status\
$time"""

format = """
[](color_orange)\
$os\
$username\
$hostname\
$sudo\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_blue)\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
[](fg:color_blue bg:color_aqua)\
$docker_context\
[](fg:color_aqua bg:color_bg1)\
$cmd_duration\
[ ](fg:color_bg1)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_aqua   = '#689d6a'
color_bg1    = '#3c3836'
color_bg3    = '#665c54'
color_blue   = '#458588'
color_fg0    = '#fbf1c7'
color_green  = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red    = '#cc241d'
color_yellow = '#d79921'

[cmd_duration]
format             = "[ took $duration]($style)"
min_time_to_notify = 180_000
show_notifications = false
style              = "fg:color_yellow bg:color_bg1"

[os]
disabled = false
style    = "bg:color_orange fg:color_fg0"

[username]
format      = '[ $user ]($style)'
show_always = true
style_root  = "bg:color_orange fg:color_fg0"
style_user  = "bg:color_orange fg:color_fg0"

[directory]
fish_style_pwd_dir_length = 3
format                    = "[ $path ]($style)"
style                     = "fg:color_fg0 bg:color_yellow"
truncate_to_repo          = false
truncation_length         = 3
truncation_symbol         = "…/"

[time]
disabled    = false
format      = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'
style       = "bg:color_bg1"
time_format = "%R"

[status]
disabled = false
format   = '[ $symbol $status]($style)'
style    = "bg:color_bg1"

[line_break]
disabled = false

[character]
disabled                  = false
error_symbol              = '[](bold fg:color_red)'
success_symbol            = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol     = '[](bold fg:color_purple)'
vimcmd_symbol             = '[](bold fg:color_green)'
vimcmd_visual_symbol      = '[](bold fg:color_yellow)'

[aws]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = "  "

[buf]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[c]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[cmake]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[conda]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[crystal]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[dart]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[docker_context]
format = '[[ $symbol( $context) ](fg:color_fg0 bg:color_aqua)]($style)'
style  = "bg:color_aqua"
symbol = " "

[elixir]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[elm]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[fennel]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[fossil_branch]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[git_branch]
format            = '[$symbol$branch(:$remote_branch)]($style)'
style             = "fg:color_fg0 bg:color_blue"
symbol            = "  "
truncation_length = 15

[git_commit]
style              = "fg:color_fg0 bg:color_blue"
tag_disabled       = false
tag_max_candidates = 2
tag_symbol         = '  '

[git_state]
style = "fg:color_red bg:color_blue"

[git_metrics]
added_style   = "fg:color_yellow bg:color_blue"
deleted_style = "fg:color_red bg:color_blue"
disabled      = false
format        = '[ ([+$added]($added_style) )([-$deleted]($deleted_style) )](bg:color_blue)'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
style  = "fg:color_fg0 bg:color_blue"

[golang]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[guix_shell]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[haskell]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[haxe]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[hg_branch]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[hostname]
format     = "[$ssh_symbol$hostname]($style)"
ssh_only   = true
ssh_symbol = " "
style      = "bg:color_orange fg:color_fg0"

[java]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[julia]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[kotlin]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[lua]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[memory_usage]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = "󰍛 "

[meson]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = "󰔷 "

[nim]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = "󰆥 "

[nix_shell]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[nodejs]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[ocaml]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[os.symbols]
AlmaLinux        = " "
Alpaquita        = " "
Alpine           = " "
Amazon           = " "
Android          = " "
Arch             = " "
Artix            = " "
CachyOS          = " "
CentOS           = " "
Debian           = " "
DragonFly        = " "
Emscripten       = " "
EndeavourOS      = " "
Fedora           = " "
FreeBSD          = " "
Garuda           = "󰛓 "
Gentoo           = " "
HardenedBSD      = "󰞌 "
Illumos          = "󰈸 "
Kali             = " "
Linux            = " "
Mabox            = " "
Macos            = " "
Manjaro          = " "
Mariner          = " "
MidnightBSD      = " "
Mint             = " "
NetBSD           = " "
NixOS            = " "
Nobara           = " "
OpenBSD          = "󰈺 "
OracleLinux      = "󰌷 "
Pop              = " "
Raspbian         = " "
RedHatEnterprise = " "
Redhat           = " "
Redox            = "󰀘 "
RockyLinux       = " "
SUSE             = " "
Solus            = "󰠳 "
Ubuntu           = " "
Unknown          = " "
Void             = " "
Windows          = "󰍲 "
openSUSE         = " "

[package]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = "󰏗 "

[perl]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[php]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[pijul_channel]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[python]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[rlang]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = "󰟔 "

[ruby]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[rust]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = "󱘗 "

[scala]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[swift]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[zig]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "

[gradle]
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'
style  = "bg:color_blue"
symbol = " "
