return {
	"folke/which-key.nvim",
	dependencies = {
		{ "echasnovski/mini.icons", version = false },
	},
	event = "VeryLazy",
	init = function()
		vim.o.timeout = true
		vim.o.timeoutlen = 300
	end,
	opts = {
		spec = {
			-- our own prefixes
			{ "<leader>b", group = "buffers / comment box", mode = { "n", "v" } },
			{ "<leader>c", group = "clipboard / chat", mode = { "n", "v" } },
			{ "<leader>ca", group = "close all" },
			{ "<leader>e", group = "edgy" },
			{ "<leader>f", group = "find" },
			{ "<leader>g", group = "git" },
			{ "<leader>G", group = "go" },
			{ "<leader>h", group = "git hunks", mode = { "n", "v" } },
			{ "<leader>p", group = "params / term copy" },
			{ "<leader>r", group = "run in terminal" },
			{ "<leader>s", group = "search", mode = { "n", "v" } },
			{ "<leader>t", group = "toggles" },
			{ "<leader>x", group = "trouble" },
			{ "<leader><leader>", group = "hop", mode = "o" },
			{ "\\", group = "local leader", mode = { "x", "t" } },
			{ "\\q", group = "quit" },
			{ "\\t", group = "terminals", mode = { "n", "t" } },
			{ ";", group = "resize" },
			{ "<space>", group = "treesj / window" },

			-- builtin / plugin prefixes that otherwise show as "N keymaps"
			{ "[", group = "prev", mode = { "n", "x", "o" } },
			{ "]", group = "next", mode = { "n", "x", "o" } },
			{ "gr", group = "lsp", mode = { "n", "x" } },
			{ "g", group = "goto / misc", mode = { "n", "x", "o" } },
			{ "z", group = "folds / spelling / scroll", mode = { "n", "x" } },
			{ "=", group = "indent" },

			-- vim-abolish
			{ "cr", desc = "Coerce case (abolish)" },

			-- vim-unimpaired (descs for its <Plug> mappings)
			{ "yo", group = "toggle option" },
			{ "[o", group = "enable option" },
			{ "]o", group = "disable option" },
			{ "[e", desc = "Move line up" },
			{ "]e", desc = "Move line down" },
			{ "[f", desc = "Previous file in directory" },
			{ "]f", desc = "Next file in directory" },
			{ "[n", desc = "Previous conflict marker", mode = { "n", "x", "o" } },
			{ "]n", desc = "Next conflict marker", mode = { "n", "x", "o" } },
			{ "[p", desc = "Put above" },
			{ "]p", desc = "Put below" },
			{ "[P", desc = "Put above" },
			{ "]P", desc = "Put below" },
			{ "<p", desc = "Put below, shift left" },
			{ ">p", desc = "Put below, shift right" },
			{ "=p", desc = "Put below, reindent" },
			{ "<P", desc = "Put above, shift left" },
			{ ">P", desc = "Put above, shift right" },
			{ "=P", desc = "Put above, reindent" },
			{ "[x", group = "XML decode" },
			{ "]x", group = "XML encode" },
			{ "[xx", desc = "XML decode line" },
			{ "]xx", desc = "XML encode line" },
			{ "[u", group = "URL decode" },
			{ "]u", group = "URL encode" },
			{ "[uu", desc = "URL decode line" },
			{ "]uu", desc = "URL encode line" },
			{ "[y", group = "C-string decode" },
			{ "]y", group = "C-string encode" },
			{ "[yy", desc = "C-string decode line" },
			{ "]yy", desc = "C-string encode line" },
			{ "[C", group = "C-string decode" },
			{ "]C", group = "C-string encode" },
			{ "[CC", desc = "C-string decode line" },
			{ "]CC", desc = "C-string encode line" },
			{ "[x", desc = "XML decode", mode = "x" },
			{ "]x", desc = "XML encode", mode = "x" },
			{ "[u", desc = "URL decode", mode = "x" },
			{ "]u", desc = "URL encode", mode = "x" },
			{ "[y", desc = "C-string decode", mode = "x" },
			{ "]y", desc = "C-string encode", mode = "x" },
			{ "[C", desc = "C-string decode", mode = "x" },
			{ "]C", desc = "C-string encode", mode = "x" },
			{ "[e", desc = "Move selection up", mode = "x" },
			{ "]e", desc = "Move selection down", mode = "x" },
			-- unimpaired's <Esc> cancel stubs and operator variants are noise
			{ "yo<Esc>", hidden = true },
			{ "[o<Esc>", hidden = true },
			{ "]o<Esc>", hidden = true },
			{ "<s", hidden = true },
			{ ">s", hidden = true },
			{ "=s", hidden = true },

			-- targets.vim
			{ "A", desc = "Around object, incl. whitespace (targets)", mode = { "x", "o" } },
			{ "I", desc = "Inside object, excl. whitespace (targets)", mode = { "x", "o" } },
			{ "@(targets)", hidden = true, mode = { "x", "o" } },

			-- better-escape
			{ "k", desc = "kj → <Esc> (better-escape)", mode = { "i", "c", "t" } },
			{ "j", desc = "kj → <Esc> (better-escape)", mode = { "i", "c", "t" } },
		},
	},
}
