function lsblkc --wraps=lsblk\ -f\ -o\ \'NAME,LABEL,TYPE,SIZE,FSAVAIL,FSUSE\%,FSTYPE,FSROOTS,MOUNTPOINTS\' --description alias\ lsblkc\ lsblk\ -f\ -o\ \'NAME,LABEL,TYPE,SIZE,FSAVAIL,FSUSE\%,FSTYPE,FSROOTS,MOUNTPOINTS\'
    lsblk -f -o 'NAME,LABEL,TYPE,SIZE,FSAVAIL,FSUSE%,FSTYPE,FSROOTS,MOUNTPOINTS' $argv

end
